[env]
_.source = './.envrc'

[tools]
task = "latest"
jq = "latest"
"ubi:docker/cagent" = "latest"

[tools."http:terraform-mcp-server"]
version = "0.2.3"

[tools."http:terraform-mcp-server".platforms]
macos-x64 = { url = "https://releases.hashicorp.com/terraform-mcp-server/0.2.3/terraform-mcp-server_0.2.3_darwin_amd64.zip" }
macos-arm64 = { url = "https://releases.hashicorp.com/terraform-mcp-server/0.2.3/terraform-mcp-server_0.2.3_darwin_arm64.zip" }
linux-x64 = { url = "https://releases.hashicorp.com/terraform-mcp-server/0.2.3/terraform-mcp-server_0.2.3_linux_amd64.zip" }
windows-x64 = { url = "https://releases.hashicorp.com/terraform-mcp-server/0.2.3/terraform-mcp-server_0.2.3_windows_amd64.zip" }